# Generated by Django 4.2.10 on 2024-03-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_number", models.IntegerField(verbose_name="床号")),
                ("patient_name", models.CharField(max_length=100, verbose_name="姓名")),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=100, verbose_name="药物名称")),
                ("dosage", models.CharField(max_length=100, verbose_name="计量")),
                (
                    "before_or_after_meal",
                    models.CharField(max_length=10, verbose_name="餐前/餐后"),
                ),
                ("is_machine_dispensed", models.BooleanField(verbose_name="是否分药机分药")),
                ("morning_dosage", models.BooleanField(verbose_name="早")),
                ("noon_dosage", models.BooleanField(verbose_name="中")),
                ("evening_dosage", models.BooleanField(verbose_name="晚")),
                ("night_dosage", models.BooleanField(verbose_name="夜")),
                (
                    "patient_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.patient"
                    ),
                ),
            ],
        ),
    ]
