# Generated by Django 4.2.10 on 2024-03-04 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
