# Generated by Django 4.2.10 on 2024-03-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0007_alter_patient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="medication",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to="User.patient",
            ),
        ),
    ]
