# Generated by Django 4.2.10 on 2024-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0008_remove_medication_patient_name_medication_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
