# Generated by Django 4.2.10 on 2024-03-15 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0010_image_user_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
    ]
